apiVersion: v1
kind: Service
metadata:
  name: image-platform-service
spec:
  type: NodePort
  selector:
    app: image-platform
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8090
    nodePort: 30080

